# Generated by Django 3.2.5 on 2021-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_sesion_fichero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
