# Generated by Django 3.2.5 on 2021-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_sesion_rondas'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='img_juego',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
