# Generated by Django 3.2.5 on 2021-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_juego_img_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='icono',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='juego',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
