# Generated by Django 3.2.5 on 2021-08-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='images/user(1).png', upload_to='images/'),
        ),
    ]
