# Generated by Django 3.2.5 on 2021-08-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
