# Generated by Django 3.2.5 on 2021-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20210824_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='tipo',
        ),
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
